#pragma once
#include <stdio.h>
#include <string>
#include <stdlib.h>
#include <time.h>
#include <iostream>
#include <exception>
#include <list>
#include <vector>
#include <cstdlib>
#include <thread>
#include <chrono>
#include <cstdlib>
#include <windows.h>
#include <numeric>
#include <fstream>
#include <map>
#include <string>
#include <math.h>
#include <numeric>
#include "Dice.h"
#include "Rules.h"
#include "Player.h"
#include "includes.h"
#include <time.h>